name: Deploy API pipeline

on:
  push:
    branches:
      - main
    paths:
      - api/**
  workflow_dispatch:

jobs:
  deploy_api:
    uses: ./.github/workflows/deploy.yml
    secrets:
      clever_token: ${{ secrets.clever_token }}
      clever_secret: ${{ secrets.clever_secret }}
      clever_app_id: ${{ secrets.api_app_id }}
